version: '3'
services:
  postgresql:
    image: postgres
    container_name: postgresql
    restart: always
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'password'
      TZ: 'Asia/Seoul'
